# -*- coding: utf-8 -*-
{
    'name': 'Diet Facts - Nutrition Reports',
    'version': '1.0.0',
    'category': 'Sales/Diet',
    'summary': 'Module for managing diet facts, nutrients, meals, and nutrition reports',
    'sequence': -100,
    'author': 'Zakaria Farih',
    'website': 'https://portfolio-eta-khaki-96.vercel.app/',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'product',
        'sale',
'portal',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/cron_job_data.xml',
        'data/categories.xml',
        'data/nutrients.xml',
        'views/dietary_goal_views.xml',
        'views/meal_schedule_views.xml',
        'views/allergen_views.xml',
        'views/water_intake_views.xml',
        'views/gamification_views.xml',
        'views/product_extension_views.xml',
        'views/recipe_suggestion_wizard_views.xml',
        'views/kanban_view.xml',
        'views/dietfacts_view.xml',
        'views/nutrients_view.xml',
        'views/nutritionfacts_view.xml',
        'views/meals_view.xml',
        'views/mealitems_view.xml',
        'views/search_views.xml',
        'views/menus.xml',
        'data/product.template.csv',
        'data/nutritionfacts_data.xml',
        'data/demo_extended_data.xml',
        'data/meal_template.xml',
        'reports/nutritionfacts_report.xml',
    ],
    'demo': [
        'data/demo_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
